version: "3"
services:
  nginx:
    build: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./symfony:/app/symfony
      - ./nginx/symfony.conf:/etc/nginx/conf.d/symfony.conf
      - ./nginx/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
      - ./nginx/entrypoint.sh:/sbin/entrypoint.sh
      - ./certs:/certs

  php:
    build: php
    ports:
      - 8000:8000
    volumes:
      - ./symfony:/app/symfony
      - ./php/www.conf:/etc/php/8.2/fpm/pool.d/www.conf
      - ./php/entrypoint.sh:/sbin/entrypoint.sh

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123.
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: abc123.
    volumes:
      - basedatos:/var/lib/mysql
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  basedatos:
